networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
services:
  mongodb:
    image: vinodkumarpaleti/mongodb:v1
    container_name: mongodb-container
    networks:
      - roboshop 
    volumes:
    - source: mongodb
      target: /data/db
      type: volume
  catalogue:
    image: vinodkumarpaleti/catalogue:v1
    container_name: catalogue-container
    networks:
      - roboshop
    depends_on:
      - mongodb
  redis:
    image: redis
    container_name: redis-container
    networks:
      - roboshop
    volumes:
    - source: redis
      target: /data
      type: volume
  user:
    image: vinodkumarpaleti/user:v1
    container_name: user-container
    networks:
      - roboshop
    depends_on:
    - mongodb
    - redis
  cart:
    image: vinodkumarpaleti/cart:v1
    container_name: cart-container
    networks:
      - roboshop
    depends_on:
    - redis
    - catalogue
  mysql:
    image: vinodkumarpaleti/mysql:v1
    container_name: mysql-container
    networks:
      - roboshop
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume
  shipping:
    image: vinodkumarpaleti/shipping:v1
    container_name: shipping-container
    networks:
      - roboshop
    depends_on:
    - cart
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - roboshop
    volumes:
    - source: rabbitmq
      target: /var/lib/rabbitmq
      type: volume
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123
  payment:
    image: vinodkumarpaleti/payment:v1
    container_name: payment
    networks:
      - roboshop
    depends_on:
      - cart
      - user
      - rabbitmq
  web:
    image: vinodkumarpaleti/web:v1
    container_name: web-container
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment